### ISSUE TITLE
MySQL upload error

### ISSUE THREAD

**Issue by ProbablyGeorgeP** [YisusTM01/loaf_housing#3]
The errors i am getting... could do with some serious help

SQL query:

ALTER TABLE users ADD COLUMN house LONGTEXT NOT NULL DEFAULT '{"owns":false,"furniture":[],"houseId":0}'
MySQL said: Documentation

#1101 - BLOB/TEXT column 'house' can't have a default value

**Comment by stijndioos** [comment]
same problem i think its a linux  sql thing . on my windows server is it working
