### ISSUE TITLE
Blinking inside interior

### ISSUE THREAD

**Issue by rex2630** [YisusTM01/loaf_housing#4]

**Comment by YisusTM01** [comment]
You should disable clear weather functions when you enter and exit, that causes the blinking because override the current weather.

**Comment by rex2630** [comment]
Thanks for your answer, but commenting this didnt helped
![image](https://user-images.githubusercontent.com/30006554/80379530-81ac8980-889e-11ea-9d6f-560fa0db3a99.png)

**Comment by YisusTM01** [comment]
![image](https://user-images.githubusercontent.com/52821987/80384283-fbe00c80-88a4-11ea-95d7-90b5776fe432.png)

There are two with same for Ikea and the house thing

**Comment by rex2630** [comment]
I tried that too and that didnt helped :/

**Comment by rex2630** [comment]
Problem is that these housing shells doesnt have any kind of collisions, it is even raining inside and u hear winter around you. Its really weird

**Comment by rex2630** [comment]
Can u message me on discord, please? Davidd#8486

**Comment by YisusTM01** [comment]
Added
