### ISSUE TITLE
Falling out of houses

### ISSUE THREAD

**Issue by BrutalFive** [YisusTM01/loaf_housing#5]
Hi, 

So I bought a house and when I'm entering I've been falling out of map. Obviously there is no interior whatsoever. Is there anything else I need to install for this to work or do I need to map an interior for each houses?

**Comment by YisusTM01** [comment]
You need House Shell you can make it with in game files or buy them...

**Comment by BrutalFive** [comment]
What a fast reply. Thank you. Meantime I found out that other have asked this already so sry for wasting your time
